<?php

return [
    'languages' => [
        'ru' => [
            'label' => 'Русский',
            'flag' => 'ru',
            'locale' => 'ru-RU',
            'appName' => 'Школа Нового Мышления в Центральной Азии',
            'license' => 'Лицензия на образовательную деятельность в сфере среднего профессионального образования выдана Министерством образования и науки Кыргызской Республики 18 сентября 2018 года. Регистрационный номер C2018-0001.',
            'menu' => [
                'news' => 'Новости',
                'contacts' => 'Контакты',
            ],
            'news' => [
                'intro' => 'Последние новости и события школы.',
                'readMore' => 'Подробнее...',
                'empty' => 'Новости пока не опубликованы.',
                'latestTitle' => 'Свежие новости',
                'allNews' => 'Все новости',
            ],
            'pages' => [
                'subpagesLabel' => 'Подстраницы',
            ],
            'contactPage' => [
                'title' => 'Контакты',
                'badge' => 'Будем рады ответить на ваши вопросы',
                'intro' => 'Мы на связи в WhatsApp, Instagram и по телефону.',
                'addressLabel' => 'Адрес',
                'address' => 'Кыргызстан, город Бишкек, улица Кольбаева 12',
                'phoneLabel' => 'Телефон',
                'whatsappLabel' => 'WhatsApp',
                'instagramLabel' => 'Instagram',
                'mapTitle' => 'Карта проезда',
                'highlights' => [
                    'Расскажем об образовательной модели и направлениях',
                    'Ответим на вопросы о поступлении и вступительном экзамене',
                    'Поможем разобраться в формате обучения и возможностях для студентов',
                ],
            ],
        ],
        'en' => [
            'label' => 'English',
            'flag' => 'us',
            'locale' => 'en-US',
            'appName' => 'New Thinking School of Central Asia',
            'license' => 'The license for educational activities in the field of secondary vocational education was issued by the Ministry of Education and Science of the Kyrgyz Republic on September 18, 2018. Registration number C2018-0001.',
            'menu' => [
                'news' => 'News',
                'contacts' => 'Contacts',
            ],
            'news' => [
                'intro' => 'Latest school news and events.',
                'readMore' => 'More details...',
                'empty' => 'No news has been published yet.',
                'latestTitle' => 'Latest news',
                'allNews' => 'All news',
            ],
            'pages' => [
                'subpagesLabel' => 'Subpages',
            ],
            'contactPage' => [
                'title' => 'Contacts',
                'badge' => 'We will be happy to answer your questions',
                'intro' => 'Reach us on WhatsApp, Instagram, or by phone.',
                'addressLabel' => 'Address',
                'address' => 'Kyrgyzstan, Bishkek, Kolbaev Street 12',
                'phoneLabel' => 'Phone',
                'whatsappLabel' => 'WhatsApp',
                'instagramLabel' => 'Instagram',
                'mapTitle' => 'Map',
                'highlights' => [
                    'We will explain the educational model and study areas',
                    'We will answer questions about admission and the entrance exam',
                    'We will help you understand the learning format and opportunities for students',
                ],
            ],
        ],
        'ky' => [
            'label' => 'Кыргызча',
            'flag' => 'kg',
            'locale' => 'ky-KG',
            'appName' => 'Борбордук Азиядагы Жаңы Ой Жүгүртүү Мектеби',
            'license' => 'Орто кесиптик билим берүү тармагындагы билим берүү ишмердүүлүгүнө лицензия Кыргыз Республикасынын Билим берүү жана илим министрлиги тарабынан 2018-жылдын 18-сентябрында берилген. Каттоо номери C2018-0001',
            'menu' => [
                'news' => 'Жаңылыктар',
                'contacts' => 'Байланыштар',
            ],
            'news' => [
                'intro' => 'Мектептин акыркы жаңылыктары жана окуялары.',
                'readMore' => 'Кененирээк...',
                'empty' => 'Азырынча жаңылыктар жарыялана элек.',
                'latestTitle' => 'Акыркы жаңылыктар',
                'allNews' => 'Бардык жаңылыктар',
            ],
            'pages' => [
                'subpagesLabel' => 'Кошумча барактар',
            ],
            'contactPage' => [
                'title' => 'Байланыштар',
                'badge' => 'Суроолоруңузга жооп берүүгө кубанычтабыз',
                'intro' => 'Биз менен WhatsApp, Instagram же телефон аркылуу байланышыңыз.',
                'addressLabel' => 'Дарек',
                'address' => 'Кыргызстан, Бишкек шаары, Кольбаев көчөсү 12',
                'phoneLabel' => 'Телефон',
                'whatsappLabel' => 'WhatsApp',
                'instagramLabel' => 'Instagram',
                'mapTitle' => 'Багыттар',
                'highlights' => [
                    'Билим берүү модели жана багыттары тууралуу айтып беребиз',
                    'Кабыл алуу жана кирүү экзамени боюнча суроолорго жооп беребиз',
                    'Окуу форматын жана студенттер үчүн мүмкүнчүлүктөрдү түшүндүрүүгө жардам беребиз',
                ],
            ],
        ],
    ],
    'defaultLanguage' => 'ru',
    'contacts' => [
        'phone' => '996558915002',
        'phoneDisplay' => '+996 558 915 002',
        'instagram' => 'https://www.instagram.com/newthinkingschool.kg/',
        'youtube' => 'https://www.youtube.com/@newthinkingschoolkg',
        'facebook' => 'https://www.facebook.com/profile.php?id=100083308430897',
        'whatsapp' => '996558915002',
        'address' => 'Кыргызстан, город Бишкек, улица Кольбаева 12',
    ],
];
